//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkiv.arkivering.arkivmelding.kvittering {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2", IsNullable=false)]
    public partial class arkivmeldingKvittering {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappeKvittering", typeof(mappeKvittering))]
        [System.Xml.Serialization.XmlElementAttribute("registreringKvittering", typeof(registreringKvittering))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saksmappeKvittering))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class mappeKvittering {
        
        private systemID systemIDField;
        
        private string mappeIDField;
        
        private systemID referanseForeldermappeField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private eksternNoekkelKvittering referanseEksternNoekkelField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        public systemID ReferanseForeldermappe {
            get {
                return this.referanseForeldermappeField;
            }
            set {
                this.referanseForeldermappeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkelKvittering referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappeKvittering", typeof(mappeKvittering))]
        [System.Xml.Serialization.XmlElementAttribute("registreringKvittering", typeof(registreringKvittering))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2")]
    public partial class systemID {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class dokumentobjektKvittering {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class dokumentbeskrivelseKvittering {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private dokumentobjektKvittering[] dokumentobjektField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public dokumentobjektKvittering[] dokumentobjekt {
            get {
                return this.dokumentobjektField;
            }
            set {
                this.dokumentobjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpostKvittering))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class registreringKvittering {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime arkivertDatoField;
        
        private bool arkivertDatoFieldSpecified;
        
        private string arkivertAvField;
        
        private dokumentbeskrivelseKvittering[] dokumentbeskrivelseKvitteringField;
        
        private string registreringsIDField;
        
        private eksternNoekkelKvittering referanseEksternNoekkelField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arkivertDato {
            get {
                return this.arkivertDatoField;
            }
            set {
                this.arkivertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arkivertDatoSpecified {
            get {
                return this.arkivertDatoFieldSpecified;
            }
            set {
                this.arkivertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string arkivertAv {
            get {
                return this.arkivertAvField;
            }
            set {
                this.arkivertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelseKvittering")]
        public dokumentbeskrivelseKvittering[] dokumentbeskrivelseKvittering {
            get {
                return this.dokumentbeskrivelseKvitteringField;
            }
            set {
                this.dokumentbeskrivelseKvitteringField = value;
            }
        }
        
        /// <remarks/>
        public string registreringsID {
            get {
                return this.registreringsIDField;
            }
            set {
                this.registreringsIDField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkelKvittering referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class eksternNoekkelKvittering {
        
        private string fagsystemField;
        
        private string noekkelField;
        
        /// <remarks/>
        public string fagsystem {
            get {
                return this.fagsystemField;
            }
            set {
                this.fagsystemField = value;
            }
        }
        
        /// <remarks/>
        public string noekkel {
            get {
                return this.noekkelField;
            }
            set {
                this.noekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class journalpostKvittering : registreringKvittering {
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private string journalposttypeField;
        
        private string journalstatusField;
        
        private System.DateTime journaldatoField;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
            }
        }
        
        /// <remarks/>
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmeldingkvittering/v2")]
    public partial class saksmappeKvittering : mappeKvittering {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private System.DateTime saksdatoField;
        
        private bool saksdatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime saksdato {
            get {
                return this.saksdatoField;
            }
            set {
                this.saksdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saksdatoSpecified {
            get {
                return this.saksdatoFieldSpecified;
            }
            set {
                this.saksdatoFieldSpecified = value;
            }
        }
    }
}
