//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkiv.arkivering.arkivmelding {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2", IsNullable=false)]
    public partial class arkivmelding {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int antallFilerField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int antallFiler {
            get {
                return this.antallFilerField;
            }
            set {
                this.antallFilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappe))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registrering))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saksmappe))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class mappe {
        
        private systemID systemIDField;
        
        private string mappeIDField;
        
        private systemID referanseForeldermappeField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private string dokumentmediumField;
        
        private string[] oppbevaringsstedField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private string[] referanseArkivdelField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        private part[] partField;
        
        private kryssreferanse[] kryssreferanseField;
        
        private merknad[] merknadField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private klassifikasjon[] klassifikasjonField;
        
        private eksternNoekkel referanseEksternNoekkelField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        public systemID ReferanseForeldermappe {
            get {
                return this.referanseForeldermappeField;
            }
            set {
                this.referanseForeldermappeField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public part[] part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanse")]
        public kryssreferanse[] kryssreferanse {
            get {
                return this.kryssreferanseField;
            }
            set {
                this.kryssreferanseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjon")]
        public klassifikasjon[] klassifikasjon {
            get {
                return this.klassifikasjonField;
            }
            set {
                this.klassifikasjonField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkel referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappe))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registrering))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2")]
    public partial class systemID {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class punkt {
        
        private string koordinatsystemField;
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        public string koordinatsystem {
            get {
                return this.koordinatsystemField;
            }
            set {
                this.koordinatsystemField = value;
            }
        }
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class planident {
        
        private string planidentifikasjonField;
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        public string planidentifikasjon {
            get {
                return this.planidentifikasjonField;
            }
            set {
                this.planidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fylkesnummer", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("kommunenummer", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("landkode", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        fylkesnummer,
        
        /// <remarks/>
        kommunenummer,
        
        /// <remarks/>
        landkode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class byggident {
        
        private string bygningsnummerField;
        
        private string endringsloepenummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string endringsloepenummer {
            get {
                return this.endringsloepenummerField;
            }
            set {
                this.endringsloepenummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class matrikkelnummer {
        
        private string kommunenummerField;
        
        private string gardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string gardsnummer {
            get {
                return this.gardsnummerField;
            }
            set {
                this.gardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public abstract partial class AbstraktNasjonalidentifikatorType {
        
        private systemID systemIDField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class hendelseslogg {
        
        private string referanseArkivenhetField;
        
        private string beskrivelseField;
        
        private string hendelsestypeField;
        
        private System.DateTime hendelsesdatoField;
        
        private string utfortAvField;
        
        /// <remarks/>
        public string referanseArkivenhet {
            get {
                return this.referanseArkivenhetField;
            }
            set {
                this.referanseArkivenhetField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string hendelsestype {
            get {
                return this.hendelsestypeField;
            }
            set {
                this.hendelsestypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime hendelsesdato {
            get {
                return this.hendelsesdatoField;
            }
            set {
                this.hendelsesdatoField = value;
            }
        }
        
        /// <remarks/>
        public string utfortAv {
            get {
                return this.utfortAvField;
            }
            set {
                this.utfortAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class presedens {
        
        private System.DateTime presedensDatoField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string presedensHjemmelField;
        
        private string rettskildefaktorField;
        
        private System.DateTime presedensGodkjentDatoField;
        
        private bool presedensGodkjentDatoFieldSpecified;
        
        private string presedensGodkjentAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private string presedensStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime presedensDato {
            get {
                return this.presedensDatoField;
            }
            set {
                this.presedensDatoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string presedensHjemmel {
            get {
                return this.presedensHjemmelField;
            }
            set {
                this.presedensHjemmelField = value;
            }
        }
        
        /// <remarks/>
        public string rettskildefaktor {
            get {
                return this.rettskildefaktorField;
            }
            set {
                this.rettskildefaktorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime presedensGodkjentDato {
            get {
                return this.presedensGodkjentDatoField;
            }
            set {
                this.presedensGodkjentDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presedensGodkjentDatoSpecified {
            get {
                return this.presedensGodkjentDatoFieldSpecified;
            }
            set {
                this.presedensGodkjentDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string presedensGodkjentAv {
            get {
                return this.presedensGodkjentAvField;
            }
            set {
                this.presedensGodkjentAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        public string presedensStatus {
            get {
                return this.presedensStatusField;
            }
            set {
                this.presedensStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class dokumentflyt {
        
        private string flytTilField;
        
        private string flytFraField;
        
        private System.DateTime flytMottattDatoField;
        
        private System.DateTime flytSendtDatoField;
        
        private string flytStatusField;
        
        private string flytMerknadField;
        
        /// <remarks/>
        public string flytTil {
            get {
                return this.flytTilField;
            }
            set {
                this.flytTilField = value;
            }
        }
        
        /// <remarks/>
        public string flytFra {
            get {
                return this.flytFraField;
            }
            set {
                this.flytFraField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flytMottattDato {
            get {
                return this.flytMottattDatoField;
            }
            set {
                this.flytMottattDatoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flytSendtDato {
            get {
                return this.flytSendtDatoField;
            }
            set {
                this.flytSendtDatoField = value;
            }
        }
        
        /// <remarks/>
        public string flytStatus {
            get {
                return this.flytStatusField;
            }
            set {
                this.flytStatusField = value;
            }
        }
        
        /// <remarks/>
        public string flytMerknad {
            get {
                return this.flytMerknadField;
            }
            set {
                this.flytMerknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class avskrivning {
        
        private System.DateTime avskrivningsdatoField;
        
        private string avskrevetAvField;
        
        private string avskrivningsmaateField;
        
        private string referanseAvskrivesAvJournalpostField;
        
        private string referanseAvskriverJournalpostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime avskrivningsdato {
            get {
                return this.avskrivningsdatoField;
            }
            set {
                this.avskrivningsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string avskrevetAv {
            get {
                return this.avskrevetAvField;
            }
            set {
                this.avskrevetAvField = value;
            }
        }
        
        /// <remarks/>
        public string avskrivningsmaate {
            get {
                return this.avskrivningsmaateField;
            }
            set {
                this.avskrivningsmaateField = value;
            }
        }
        
        /// <remarks/>
        public string referanseAvskrivesAvJournalpost {
            get {
                return this.referanseAvskrivesAvJournalpostField;
            }
            set {
                this.referanseAvskrivesAvJournalpostField = value;
            }
        }
        
        /// <remarks/>
        public string referanseAvskriverJournalpost {
            get {
                return this.referanseAvskriverJournalpostField;
            }
            set {
                this.referanseAvskriverJournalpostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class eksternNoekkel {
        
        private string fagsystemField;
        
        private string noekkelField;
        
        /// <remarks/>
        public string fagsystem {
            get {
                return this.fagsystemField;
            }
            set {
                this.fagsystemField = value;
            }
        }
        
        /// <remarks/>
        public string noekkel {
            get {
                return this.noekkelField;
            }
            set {
                this.noekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class klassifikasjon {
        
        private systemID systemIDField;
        
        private string klassifikasjonssystemField;
        
        private string klasseIDField;
        
        private string tittelField;
        
        private string skjermetObjektField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string klassifikasjonssystem {
            get {
                return this.klassifikasjonssystemField;
            }
            set {
                this.klassifikasjonssystemField = value;
            }
        }
        
        /// <remarks/>
        public string klasseID {
            get {
                return this.klasseIDField;
            }
            set {
                this.klasseIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string skjermetObjekt {
            get {
                return this.skjermetObjektField;
            }
            set {
                this.skjermetObjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class korrespondansepart {
        
        private systemID systemIDField;
        
        private string korrespondanseparttypeField;
        
        private string korrespondansepartNavnField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string[] postadresseField;
        
        private string postnummerField;
        
        private string poststedField;
        
        private string landField;
        
        private string epostadresseField;
        
        private string[] telefonnummerField;
        
        private string kontaktpersonField;
        
        private string administrativEnhetField;
        
        private string saksbehandlerField;
        
        private string skjermetObjektField;
        
        private string personnavnField;
        
        private string forsendelsesmaateField;
        
        private string deresReferanseField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string korrespondanseparttype {
            get {
                return this.korrespondanseparttypeField;
            }
            set {
                this.korrespondanseparttypeField = value;
            }
        }
        
        /// <remarks/>
        public string korrespondansepartNavn {
            get {
                return this.korrespondansepartNavnField;
            }
            set {
                this.korrespondansepartNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organisasjonid", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("personid", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postadresse")]
        public string[] postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
            }
        }
        
        /// <remarks/>
        public string postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public string epostadresse {
            get {
                return this.epostadresseField;
            }
            set {
                this.epostadresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefonnummer")]
        public string[] telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        public string kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksbehandler {
            get {
                return this.saksbehandlerField;
            }
            set {
                this.saksbehandlerField = value;
            }
        }
        
        /// <remarks/>
        public string skjermetObjekt {
            get {
                return this.skjermetObjektField;
            }
            set {
                this.skjermetObjektField = value;
            }
        }
        
        /// <remarks/>
        public string personnavn {
            get {
                return this.personnavnField;
            }
            set {
                this.personnavnField = value;
            }
        }
        
        /// <remarks/>
        public string forsendelsesmaate {
            get {
                return this.forsendelsesmaateField;
            }
            set {
                this.forsendelsesmaateField = value;
            }
        }
        
        /// <remarks/>
        public string deresReferanse {
            get {
                return this.deresReferanseField;
            }
            set {
                this.deresReferanseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        organisasjonid,
        
        /// <remarks/>
        personid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class kryssreferanse {
        
        private string referanseTilKlasseField;
        
        private string referanseTilMappeField;
        
        private string referanseTilRegistreringField;
        
        private string referanseTilDokumentbeskrivelseField;
        
        /// <remarks/>
        public string referanseTilKlasse {
            get {
                return this.referanseTilKlasseField;
            }
            set {
                this.referanseTilKlasseField = value;
            }
        }
        
        /// <remarks/>
        public string referanseTilMappe {
            get {
                return this.referanseTilMappeField;
            }
            set {
                this.referanseTilMappeField = value;
            }
        }
        
        /// <remarks/>
        public string referanseTilRegistrering {
            get {
                return this.referanseTilRegistreringField;
            }
            set {
                this.referanseTilRegistreringField = value;
            }
        }
        
        /// <remarks/>
        public string referanseTilDokumentbeskrivelse {
            get {
                return this.referanseTilDokumentbeskrivelseField;
            }
            set {
                this.referanseTilDokumentbeskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class dokumentobjekt {
        
        private systemID systemIDField;
        
        private string versjonsnummerField;
        
        private string variantformatField;
        
        private string formatField;
        
        private string formatDetaljerField;
        
        private string mimeTypeField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private string filnavnField;
        
        private string referanseDokumentfilField;
        
        private string sjekksumField;
        
        private string sjekksumAlgoritmeField;
        
        private string filstoerrelseField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string versjonsnummer {
            get {
                return this.versjonsnummerField;
            }
            set {
                this.versjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        public string variantformat {
            get {
                return this.variantformatField;
            }
            set {
                this.variantformatField = value;
            }
        }
        
        /// <remarks/>
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string formatDetaljer {
            get {
                return this.formatDetaljerField;
            }
            set {
                this.formatDetaljerField = value;
            }
        }
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string filnavn {
            get {
                return this.filnavnField;
            }
            set {
                this.filnavnField = value;
            }
        }
        
        /// <remarks/>
        public string referanseDokumentfil {
            get {
                return this.referanseDokumentfilField;
            }
            set {
                this.referanseDokumentfilField = value;
            }
        }
        
        /// <remarks/>
        public string sjekksum {
            get {
                return this.sjekksumField;
            }
            set {
                this.sjekksumField = value;
            }
        }
        
        /// <remarks/>
        public string sjekksumAlgoritme {
            get {
                return this.sjekksumAlgoritmeField;
            }
            set {
                this.sjekksumAlgoritmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string filstoerrelse {
            get {
                return this.filstoerrelseField;
            }
            set {
                this.filstoerrelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class merknad {
        
        private systemID systemIDField;
        
        private string merknadstekstField;
        
        private string merknadstypeField;
        
        private System.DateTime merknadsdatoField;
        
        private string merknadRegistrertAvField;
        
        private string skjermetObjektField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string merknadstekst {
            get {
                return this.merknadstekstField;
            }
            set {
                this.merknadstekstField = value;
            }
        }
        
        /// <remarks/>
        public string merknadstype {
            get {
                return this.merknadstypeField;
            }
            set {
                this.merknadstypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime merknadsdato {
            get {
                return this.merknadsdatoField;
            }
            set {
                this.merknadsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string merknadRegistrertAv {
            get {
                return this.merknadRegistrertAvField;
            }
            set {
                this.merknadRegistrertAvField = value;
            }
        }
        
        /// <remarks/>
        public string skjermetObjekt {
            get {
                return this.skjermetObjektField;
            }
            set {
                this.skjermetObjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class dokumentbeskrivelse {
        
        private systemID systemIDField;
        
        private string dokumenttypeField;
        
        private string dokumentstatusField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string[] forfatterField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private string dokumentmediumField;
        
        private string oppbevaringsstedField;
        
        private string[] referanseArkivdelField;
        
        private string tilknyttetRegistreringSomField;
        
        private string dokumentnummerField;
        
        private System.DateTime tilknyttetDatoField;
        
        private bool tilknyttetDatoFieldSpecified;
        
        private string tilknyttetAvField;
        
        private part[] partField;
        
        private merknad[] merknadField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private dokumentobjekt[] dokumentobjektField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string dokumenttype {
            get {
                return this.dokumenttypeField;
            }
            set {
                this.dokumenttypeField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentstatus {
            get {
                return this.dokumentstatusField;
            }
            set {
                this.dokumentstatusField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        public string oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public string tilknyttetRegistreringSom {
            get {
                return this.tilknyttetRegistreringSomField;
            }
            set {
                this.tilknyttetRegistreringSomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string dokumentnummer {
            get {
                return this.dokumentnummerField;
            }
            set {
                this.dokumentnummerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tilknyttetDato {
            get {
                return this.tilknyttetDatoField;
            }
            set {
                this.tilknyttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tilknyttetDatoSpecified {
            get {
                return this.tilknyttetDatoFieldSpecified;
            }
            set {
                this.tilknyttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tilknyttetAv {
            get {
                return this.tilknyttetAvField;
            }
            set {
                this.tilknyttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public part[] part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public dokumentobjekt[] dokumentobjekt {
            get {
                return this.dokumentobjektField;
            }
            set {
                this.dokumentobjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class part {
        
        private string partIDField;
        
        private string partNavnField;
        
        private string partRolleField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string[] postadresseField;
        
        private string postnummerField;
        
        private string poststedField;
        
        private string landField;
        
        private string epostadresseField;
        
        private string[] telefonnummerField;
        
        private string kontaktpersonField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        private string skjermetObjektField;
        
        private string personnavnField;
        
        /// <remarks/>
        public string partID {
            get {
                return this.partIDField;
            }
            set {
                this.partIDField = value;
            }
        }
        
        /// <remarks/>
        public string partNavn {
            get {
                return this.partNavnField;
            }
            set {
                this.partNavnField = value;
            }
        }
        
        /// <remarks/>
        public string partRolle {
            get {
                return this.partRolleField;
            }
            set {
                this.partRolleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organisasjonid", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("personid", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postadresse")]
        public string[] postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
            }
        }
        
        /// <remarks/>
        public string postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public string epostadresse {
            get {
                return this.epostadresseField;
            }
            set {
                this.epostadresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefonnummer")]
        public string[] telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        public string kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
        
        /// <remarks/>
        public string skjermetObjekt {
            get {
                return this.skjermetObjektField;
            }
            set {
                this.skjermetObjektField = value;
            }
        }
        
        /// <remarks/>
        public string personnavn {
            get {
                return this.personnavnField;
            }
            set {
                this.personnavnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        organisasjonid,
        
        /// <remarks/>
        personid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class skjerming {
        
        private string tilgangsrestriksjonField;
        
        private string skjermingshjemmelField;
        
        private string[] skjermingMetadataField;
        
        private string skjermingDokumentField;
        
        private string skjermingsvarighetField;
        
        private System.DateTime skjermingOpphoererDatoField;
        
        private bool skjermingOpphoererDatoFieldSpecified;
        
        /// <remarks/>
        public string tilgangsrestriksjon {
            get {
                return this.tilgangsrestriksjonField;
            }
            set {
                this.tilgangsrestriksjonField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingshjemmel {
            get {
                return this.skjermingshjemmelField;
            }
            set {
                this.skjermingshjemmelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("skjermingMetadata")]
        public string[] skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingDokument {
            get {
                return this.skjermingDokumentField;
            }
            set {
                this.skjermingDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string skjermingsvarighet {
            get {
                return this.skjermingsvarighetField;
            }
            set {
                this.skjermingsvarighetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime skjermingOpphoererDato {
            get {
                return this.skjermingOpphoererDatoField;
            }
            set {
                this.skjermingOpphoererDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skjermingOpphoererDatoSpecified {
            get {
                return this.skjermingOpphoererDatoFieldSpecified;
            }
            set {
                this.skjermingOpphoererDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class gradering {
        
        private string gradField;
        
        private System.DateTime graderingsdatoField;
        
        private string gradertAvField;
        
        private System.DateTime nedgraderingsdatoField;
        
        private bool nedgraderingsdatoFieldSpecified;
        
        private string nedgradertAvField;
        
        /// <remarks/>
        public string grad {
            get {
                return this.gradField;
            }
            set {
                this.gradField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime graderingsdato {
            get {
                return this.graderingsdatoField;
            }
            set {
                this.graderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string gradertAv {
            get {
                return this.gradertAvField;
            }
            set {
                this.gradertAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime nedgraderingsdato {
            get {
                return this.nedgraderingsdatoField;
            }
            set {
                this.nedgraderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nedgraderingsdatoSpecified {
            get {
                return this.nedgraderingsdatoFieldSpecified;
            }
            set {
                this.nedgraderingsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string nedgradertAv {
            get {
                return this.nedgradertAvField;
            }
            set {
                this.nedgradertAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(arkivnotat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpost))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class registrering {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime arkivertDatoField;
        
        private bool arkivertDatoFieldSpecified;
        
        private string arkivertAvField;
        
        private object itemField;
        
        private part[] partField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private dokumentbeskrivelse[] dokumentbeskrivelseField;
        
        private string registreringsIDField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private string[] forfatterField;
        
        private string dokumentmediumField;
        
        private string[] oppbevaringsstedField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        private merknad[] merknadField;
        
        private kryssreferanse[] kryssreferanseField;
        
        private korrespondansepart[] korrespondansepartField;
        
        private klassifikasjon[] klassifikasjonField;
        
        private eksternNoekkel referanseEksternNoekkelField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arkivertDato {
            get {
                return this.arkivertDatoField;
            }
            set {
                this.arkivertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arkivertDatoSpecified {
            get {
                return this.arkivertDatoFieldSpecified;
            }
            set {
                this.arkivertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string arkivertAv {
            get {
                return this.arkivertAvField;
            }
            set {
                this.arkivertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("referanseForelderMappe", typeof(systemID))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public part[] part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public dokumentbeskrivelse[] dokumentbeskrivelse {
            get {
                return this.dokumentbeskrivelseField;
            }
            set {
                this.dokumentbeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string registreringsID {
            get {
                return this.registreringsIDField;
            }
            set {
                this.registreringsIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanse")]
        public kryssreferanse[] kryssreferanse {
            get {
                return this.kryssreferanseField;
            }
            set {
                this.kryssreferanseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepart")]
        public korrespondansepart[] korrespondansepart {
            get {
                return this.korrespondansepartField;
            }
            set {
                this.korrespondansepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjon")]
        public klassifikasjon[] klassifikasjon {
            get {
                return this.klassifikasjonField;
            }
            set {
                this.klassifikasjonField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkel referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class arkivnotat : registrering {
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime mottattDatoField;
        
        private bool mottattDatoFieldSpecified;
        
        private System.DateTime sendtDatoField;
        
        private bool sendtDatoFieldSpecified;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        private System.DateTime offentlighetsvurdertDatoField;
        
        private bool offentlighetsvurdertDatoFieldSpecified;
        
        private string antallVedleggField;
        
        private System.DateTime utlaantDatoField;
        
        private bool utlaantDatoFieldSpecified;
        
        private string utlaantTilField;
        
        private dokumentflyt[] dokumentflytField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mottattDato {
            get {
                return this.mottattDatoField;
            }
            set {
                this.mottattDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mottattDatoSpecified {
            get {
                return this.mottattDatoFieldSpecified;
            }
            set {
                this.mottattDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sendtDato {
            get {
                return this.sendtDatoField;
            }
            set {
                this.sendtDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendtDatoSpecified {
            get {
                return this.sendtDatoFieldSpecified;
            }
            set {
                this.sendtDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime offentlighetsvurdertDato {
            get {
                return this.offentlighetsvurdertDatoField;
            }
            set {
                this.offentlighetsvurdertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offentlighetsvurdertDatoSpecified {
            get {
                return this.offentlighetsvurdertDatoFieldSpecified;
            }
            set {
                this.offentlighetsvurdertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string antallVedlegg {
            get {
                return this.antallVedleggField;
            }
            set {
                this.antallVedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime utlaantDato {
            get {
                return this.utlaantDatoField;
            }
            set {
                this.utlaantDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utlaantDatoSpecified {
            get {
                return this.utlaantDatoFieldSpecified;
            }
            set {
                this.utlaantDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string utlaantTil {
            get {
                return this.utlaantTilField;
            }
            set {
                this.utlaantTilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentflyt")]
        public dokumentflyt[] dokumentflyt {
            get {
                return this.dokumentflytField;
            }
            set {
                this.dokumentflytField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class journalpost : registrering {
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private string journalposttypeField;
        
        private string journalstatusField;
        
        private System.DateTime journaldatoField;
        
        private bool journaldatoFieldSpecified;
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime mottattDatoField;
        
        private bool mottattDatoFieldSpecified;
        
        private System.DateTime sendtDatoField;
        
        private bool sendtDatoFieldSpecified;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        private System.DateTime offentlighetsvurdertDatoField;
        
        private bool offentlighetsvurdertDatoFieldSpecified;
        
        private string antallVedleggField;
        
        private System.DateTime utlaantDatoField;
        
        private bool utlaantDatoFieldSpecified;
        
        private string utlaantTilField;
        
        private string journalenhetField;
        
        private avskrivning[] avskrivningField;
        
        private dokumentflyt[] dokumentflytField;
        
        private presedens[] presedensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
            }
        }
        
        /// <remarks/>
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool journaldatoSpecified {
            get {
                return this.journaldatoFieldSpecified;
            }
            set {
                this.journaldatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mottattDato {
            get {
                return this.mottattDatoField;
            }
            set {
                this.mottattDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mottattDatoSpecified {
            get {
                return this.mottattDatoFieldSpecified;
            }
            set {
                this.mottattDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sendtDato {
            get {
                return this.sendtDatoField;
            }
            set {
                this.sendtDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendtDatoSpecified {
            get {
                return this.sendtDatoFieldSpecified;
            }
            set {
                this.sendtDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime offentlighetsvurdertDato {
            get {
                return this.offentlighetsvurdertDatoField;
            }
            set {
                this.offentlighetsvurdertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offentlighetsvurdertDatoSpecified {
            get {
                return this.offentlighetsvurdertDatoFieldSpecified;
            }
            set {
                this.offentlighetsvurdertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string antallVedlegg {
            get {
                return this.antallVedleggField;
            }
            set {
                this.antallVedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime utlaantDato {
            get {
                return this.utlaantDatoField;
            }
            set {
                this.utlaantDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utlaantDatoSpecified {
            get {
                return this.utlaantDatoFieldSpecified;
            }
            set {
                this.utlaantDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string utlaantTil {
            get {
                return this.utlaantTilField;
            }
            set {
                this.utlaantTilField = value;
            }
        }
        
        /// <remarks/>
        public string journalenhet {
            get {
                return this.journalenhetField;
            }
            set {
                this.journalenhetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avskrivning")]
        public avskrivning[] avskrivning {
            get {
                return this.avskrivningField;
            }
            set {
                this.avskrivningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentflyt")]
        public dokumentflyt[] dokumentflyt {
            get {
                return this.dokumentflytField;
            }
            set {
                this.dokumentflytField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public presedens[] presedens {
            get {
                return this.presedensField;
            }
            set {
                this.presedensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding/v2")]
    public partial class saksmappe : mappe {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private System.DateTime saksdatoField;
        
        private bool saksdatoFieldSpecified;
        
        private string administrativEnhetField;
        
        private string saksansvarligField;
        
        private string journalenhetField;
        
        private string saksstatusField;
        
        private System.DateTime utlaantDatoField;
        
        private bool utlaantDatoFieldSpecified;
        
        private string utlaantTilField;
        
        private presedens[] presedensField;
        
        private matrikkelnummer[] matrikkelnummerField;
        
        private byggident[] byggidentField;
        
        private planident[] planidentField;
        
        private punkt[] punktField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime saksdato {
            get {
                return this.saksdatoField;
            }
            set {
                this.saksdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saksdatoSpecified {
            get {
                return this.saksdatoFieldSpecified;
            }
            set {
                this.saksdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksansvarlig {
            get {
                return this.saksansvarligField;
            }
            set {
                this.saksansvarligField = value;
            }
        }
        
        /// <remarks/>
        public string journalenhet {
            get {
                return this.journalenhetField;
            }
            set {
                this.journalenhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksstatus {
            get {
                return this.saksstatusField;
            }
            set {
                this.saksstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime utlaantDato {
            get {
                return this.utlaantDatoField;
            }
            set {
                this.utlaantDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utlaantDatoSpecified {
            get {
                return this.utlaantDatoFieldSpecified;
            }
            set {
                this.utlaantDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string utlaantTil {
            get {
                return this.utlaantTilField;
            }
            set {
                this.utlaantTilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public presedens[] presedens {
            get {
                return this.presedensField;
            }
            set {
                this.presedensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matrikkelnummer")]
        public matrikkelnummer[] matrikkelnummer {
            get {
                return this.matrikkelnummerField;
            }
            set {
                this.matrikkelnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("byggident")]
        public byggident[] byggident {
            get {
                return this.byggidentField;
            }
            set {
                this.byggidentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("planident")]
        public planident[] planident {
            get {
                return this.planidentField;
            }
            set {
                this.planidentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("punkt")]
        public punkt[] punkt {
            get {
                return this.punktField;
            }
            set {
                this.punktField = value;
            }
        }
    }
}
