//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkiv.innsyn.mappe.hent {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/mappe/hent/v2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/mappe/hent/v2", IsNullable=false)]
    public partial class mappeHent {
        
        private systemID systemIDField;
        
        private string mappeIDField;
        
        private eksternNoekkel referanseEksternNoekkelField;
        
        private responsType responsTypeField;
        
        private inkluder inkluderField;
        
        private bool inkluderFieldSpecified;
        
        public mappeHent() {
            this.responsTypeField = responsType.minimum;
        }
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkel referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
        
        /// <remarks/>
        public responsType responsType {
            get {
                return this.responsTypeField;
            }
            set {
                this.responsTypeField = value;
            }
        }
        
        /// <remarks/>
        public inkluder inkluder {
            get {
                return this.inkluderField;
            }
            set {
                this.inkluderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inkluderSpecified {
            get {
                return this.inkluderFieldSpecified;
            }
            set {
                this.inkluderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2")]
    public partial class systemID {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/mappe/hent/v2")]
    public partial class eksternNoekkel {
        
        private string fagsystemField;
        
        private string noekkelField;
        
        /// <remarks/>
        public string fagsystem {
            get {
                return this.fagsystemField;
            }
            set {
                this.fagsystemField = value;
            }
        }
        
        /// <remarks/>
        public string noekkel {
            get {
                return this.noekkelField;
            }
            set {
                this.noekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/mappe/hent/v2")]
    public enum responsType {
        
        /// <remarks/>
        noekler,
        
        /// <remarks/>
        minimum,
        
        /// <remarks/>
        utvidet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/mappe/hent/v2")]
    public enum inkluder {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        klasse,
        
        /// <remarks/>
        noekkelord,
        
        /// <remarks/>
        kryssreferanse,
        
        /// <remarks/>
        part,
        
        /// <remarks/>
        merknad,
        
        /// <remarks/>
        presedens,
        
        /// <remarks/>
        moetedeltaker,
        
        /// <remarks/>
        dokumentbeskrivelse,
        
        /// <remarks/>
        korrespondansepart,
        
        /// <remarks/>
        avskrivning,
        
        /// <remarks/>
        dokumentflyt,
        
        /// <remarks/>
        dokumentobjekt,
    }
}
