//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkivmelding.innsyn.sok {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1", IsNullable=false)]
    public partial class sok {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int takeField;
        
        private int skipField;
        
        private respons responsField;
        
        private parameter[] parameterField;
        
        private responsType responsTypeField;
        
        private inkluder inkluderField;
        
        private bool inkluderFieldSpecified;
        
        private sortering[] sorteringField;
        
        public sok() {
            this.responsTypeField = responsType.minimum;
        }
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int take {
            get {
                return this.takeField;
            }
            set {
                this.takeField = value;
            }
        }
        
        /// <remarks/>
        public int skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        public respons respons {
            get {
                return this.responsField;
            }
            set {
                this.responsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public responsType responsType {
            get {
                return this.responsTypeField;
            }
            set {
                this.responsTypeField = value;
            }
        }
        
        /// <remarks/>
        public inkluder inkluder {
            get {
                return this.inkluderField;
            }
            set {
                this.inkluderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inkluderSpecified {
            get {
                return this.inkluderFieldSpecified;
            }
            set {
                this.inkluderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sortering")]
        public sortering[] sortering {
            get {
                return this.sorteringField;
            }
            set {
                this.sorteringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum respons {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        saksmappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        journalpost,
        
        /// <remarks/>
        dokumentbeskrivelse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class parameter {
        
        private sokFelt feltField;
        
        private operatorType operatorField;
        
        private parameterverdier parameterverdierField;
        
        /// <remarks/>
        public sokFelt felt {
            get {
                return this.feltField;
            }
            set {
                this.feltField = value;
            }
        }
        
        /// <remarks/>
        public operatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public parameterverdier parameterverdier {
            get {
                return this.parameterverdierField;
            }
            set {
                this.parameterverdierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum sokFelt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.eksternId")]
        mappeeksternId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.tittel")]
        mappetittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.opprettetDato")]
        mappeopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.beskrivelse")]
        mappebeskrivelse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.noekkelord")]
        mappenoekkelord,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.avsluttetDato")]
        mappeavsluttetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.virksomhetsspesifikkeMetadata")]
        mappevirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.referansearkivdel")]
        mappereferansearkivdel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksdato")]
        saksaksdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksaar")]
        saksaksaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksekvensnummer")]
        saksaksekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksstatus")]
        saksaksstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.administrativenhet")]
        sakadministrativenhet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksansvarlig")]
        saksaksansvarlig,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.klasse.klassifikasjonssystem")]
        mappeklasseklassifikasjonssystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.klasse.klasseID")]
        mappeklasseklasseID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.klasse.tittel")]
        mappeklassetittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.klasse.beskrivelse")]
        mappeklassebeskrivelse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.partNavn")]
        mappepartpartNavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.partRolle")]
        mappepartpartRolle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.postadresse")]
        mappepartpostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.postnummer")]
        mappepartpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.poststed")]
        mappepartpoststed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.epostadresse")]
        mappepartepostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.virksomhetsspesifikkeMetadata")]
        mappepartvirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.skjerming.tilgangsrestriksjon")]
        mappeskjermingtilgangsrestriksjon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.skjerming.skjermingshjemmel")]
        mappeskjermingskjermingshjemmel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.skjerming.skjermingsvarighet")]
        mappeskjermingskjermingsvarighet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.skjerming.skjermingOpphoererDato")]
        mappeskjermingskjermingOpphoererDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.matrikkelnummer.kommunenummer")]
        sakmatrikkelnummerkommunenummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.matrikkelnummer.gaardsnummer")]
        sakmatrikkelnummergaardsnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.matrikkelnummer.bruksnummer")]
        sakmatrikkelnummerbruksnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.matrikkelnummer.festenummer")]
        sakmatrikkelnummerfestenummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.matrikkelnummer.seksjonsnummer")]
        sakmatrikkelnummerseksjonsnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.byggident.bygningsnummer")]
        sakbyggidentbygningsnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.byggident.endringsloepenummer")]
        sakbyggidentendringsloepenummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.planident.stat.landkode")]
        sakplanidentstatlandkode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.planident.fylke.fylkesnummer")]
        sakplanidentfylkefylkesnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.planident.kommune.kommunenummer")]
        sakplanidentkommunekommunenummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.planident.planidentifikasjon")]
        sakplanidentplanidentifikasjon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.punkt.x")]
        sakpunktx,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.punkt.y")]
        sakpunkty,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.punkt.z")]
        sakpunktz,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.eksternId")]
        registreringeksternId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.opprettetDato")]
        registreringopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.tittel")]
        registreringtittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.administrativenhet")]
        registreringadministrativenhet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.journalpostansvarlig")]
        registreringjournalpostansvarlig,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.partNavn")]
        registreringpartpartNavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.partRolle")]
        registreringpartpartRolle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.postadresse")]
        registreringpartpostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.postnummer")]
        registreringpartpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.poststed")]
        registreringpartpoststed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.epostadresse")]
        registreringpartepostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.virksomhetsspesifikkeMetadata")]
        registreringpartvirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.skjerming.tilgangsrestriksjon")]
        registreringskjermingtilgangsrestriksjon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.skjerming.skjermingshjemmel")]
        registreringskjermingskjermingshjemmel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.skjerming.skjermingsvarighet")]
        registreringskjermingskjermingsvarighet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.skjerming.skjermingOpphoererDato")]
        registreringskjermingskjermingOpphoererDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalaar")]
        journalpostjournalaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalsekvensnummer")]
        journalpostjournalsekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.saksaar")]
        journalpostsaksaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.sakssekvensnummer")]
        journalpostsakssekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalpostnummer")]
        journalpostjournalpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalposttype")]
        journalpostjournalposttype,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalstatus")]
        journalpostjournalstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journaldato")]
        journalpostjournaldato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.dokumentetsdato")]
        journalpostdokumentetsdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.forfallsdato")]
        journalpostforfallsdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.eksternId")]
        dokumentbeskrivelseeksternId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.opprettetDato")]
        dokumentbeskrivelseopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.tittel")]
        dokumentbeskrivelsetittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.dokumenttype")]
        dokumentbeskrivelsedokumenttype,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.dokumentstatus")]
        dokumentbeskrivelsedokumentstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.skjerming.tilgangsrestriksjon")]
        dokumentbeskrivelseskjermingtilgangsrestriksjon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.skjerming.skjermingshjemmel")]
        dokumentbeskrivelseskjermingskjermingshjemmel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.skjerming.skjermingsvarighet")]
        dokumentbeskrivelseskjermingskjermingsvarighet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.skjerming.skjermingOpphoererDato")]
        dokumentbeskrivelseskjermingskjermingOpphoererDato,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum operatorType {
        
        /// <remarks/>
        equal,
        
        /// <remarks/>
        notequal,
        
        /// <remarks/>
        between,
        
        /// <remarks/>
        lessthan,
        
        /// <remarks/>
        lessequal,
        
        /// <remarks/>
        greaterthan,
        
        /// <remarks/>
        greaterequal,
        
        /// <remarks/>
        inlist,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class parameterverdier {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datevalues", typeof(datevalues))]
        [System.Xml.Serialization.XmlElementAttribute("eksternId", typeof(eksternId))]
        [System.Xml.Serialization.XmlElementAttribute("intvalues", typeof(intvalues))]
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonvalues", typeof(klassifikasjonvalues))]
        [System.Xml.Serialization.XmlElementAttribute("stringvalues", typeof(stringvalues))]
        [System.Xml.Serialization.XmlElementAttribute("virksomhetsspesifikkemetadata", typeof(vsmetadata))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class datevalues {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public System.DateTime[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class sortering {
        
        private sorteringFelt feltField;
        
        private sorteringType typeField;
        
        /// <remarks/>
        public sorteringFelt felt {
            get {
                return this.feltField;
            }
            set {
                this.feltField = value;
            }
        }
        
        /// <remarks/>
        public sorteringType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum sorteringFelt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.opprettetDato")]
        mappeopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.avsluttetDato")]
        mappeavsluttetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.referansearkivdel")]
        mappereferansearkivdel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksdato")]
        saksaksdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksaar")]
        saksaksaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksekvensnummer")]
        saksaksekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksstatus")]
        saksaksstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.administrativenhet")]
        sakadministrativenhet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksansvarlig")]
        saksaksansvarlig,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.opprettetDato")]
        registreringopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.administrativenhet")]
        registreringadministrativenhet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.journalpostansvarlig")]
        registreringjournalpostansvarlig,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalaar")]
        journalpostjournalaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalsekvensnummer")]
        journalpostjournalsekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.saksaar")]
        journalpostsaksaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.sakssekvensnummer")]
        journalpostsakssekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalpostnummer")]
        journalpostjournalpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalposttype")]
        journalpostjournalposttype,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalstatus")]
        journalpostjournalstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journaldato")]
        journalpostjournaldato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.dokumentetsdato")]
        journalpostdokumentetsdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.forfallsdato")]
        journalpostforfallsdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.opprettetDato")]
        dokumentbeskrivelseopprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.dokumenttype")]
        dokumentbeskrivelsedokumenttype,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse.dokumentstatus")]
        dokumentbeskrivelsedokumentstatus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum sorteringType {
        
        /// <remarks/>
        synkende,
        
        /// <remarks/>
        stigende,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class vsmetadata {
        
        private string[] keyField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("key")]
        public string[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class klassifikasjonvalues {
        
        private string[] klassifikasjonssystemField;
        
        private string[] klasseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonssystem")]
        public string[] klassifikasjonssystem {
            get {
                return this.klassifikasjonssystemField;
            }
            set {
                this.klassifikasjonssystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klasse")]
        public string[] klasse {
            get {
                return this.klasseField;
            }
            set {
                this.klasseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class eksternId {
        
        private string systemField;
        
        private string idField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class intvalues {
        
        private int[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public int[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public partial class stringvalues {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum responsType {
        
        /// <remarks/>
        noekler,
        
        /// <remarks/>
        minimum,
        
        /// <remarks/>
        utvidet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1")]
    public enum inkluder {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        klasse,
        
        /// <remarks/>
        noekkelord,
        
        /// <remarks/>
        kryssreferanse,
        
        /// <remarks/>
        part,
        
        /// <remarks/>
        merknad,
        
        /// <remarks/>
        presedens,
        
        /// <remarks/>
        moetedeltaker,
        
        /// <remarks/>
        dokumentbeskrivelse,
        
        /// <remarks/>
        korrespondansepart,
        
        /// <remarks/>
        avskrivning,
        
        /// <remarks/>
        dokumentflyt,
        
        /// <remarks/>
        dokumentobjekt,
    }
}
