//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkiv.innsyn.sok.resultat.noekler {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1", IsNullable=false)]
    public partial class sokeresultatNoekler {
        
        private string systemField;
        
        private string meldingIdField;
        
        private string svarPaMeldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int takeField;
        
        private int skipField;
        
        private int countField;
        
        private resultatTypeNoekler resultattypeField;
        
        private resultatNoekler[] resultatListeField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public string svarPaMeldingId {
            get {
                return this.svarPaMeldingIdField;
            }
            set {
                this.svarPaMeldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int take {
            get {
                return this.takeField;
            }
            set {
                this.takeField = value;
            }
        }
        
        /// <remarks/>
        public int skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public resultatTypeNoekler resultattype {
            get {
                return this.resultattypeField;
            }
            set {
                this.resultattypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public resultatNoekler[] resultatListe {
            get {
                return this.resultatListeField;
            }
            set {
                this.resultatListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    public enum resultatTypeNoekler {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        saksmappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        journalpost,
        
        /// <remarks/>
        dokumentbeskrivelse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    public partial class resultatNoekler {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse", typeof(dokumentbeskrivelseNoekler))]
        [System.Xml.Serialization.XmlElementAttribute("journalpost", typeof(journalpostNoekler))]
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappeNoekler))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registreringNoekler))]
        [System.Xml.Serialization.XmlElementAttribute("saksmappe", typeof(saksmappeNoekler))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class dokumentbeskrivelseNoekler {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2")]
    public partial class systemID {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpostNoekler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class registreringNoekler {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime arkivertDatoField;
        
        private bool arkivertDatoFieldSpecified;
        
        private string arkivertAvField;
        
        private object itemField;
        
        private dokumentbeskrivelseNoekler[] dokumentbeskrivelseField;
        
        private string registreringsIDField;
        
        private eksternNoekkel referanseEksternNoekkelField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arkivertDato {
            get {
                return this.arkivertDatoField;
            }
            set {
                this.arkivertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arkivertDatoSpecified {
            get {
                return this.arkivertDatoFieldSpecified;
            }
            set {
                this.arkivertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string arkivertAv {
            get {
                return this.arkivertAvField;
            }
            set {
                this.arkivertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("referanseForelderMappe", typeof(systemID))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public dokumentbeskrivelseNoekler[] dokumentbeskrivelse {
            get {
                return this.dokumentbeskrivelseField;
            }
            set {
                this.dokumentbeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string registreringsID {
            get {
                return this.registreringsIDField;
            }
            set {
                this.registreringsIDField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkel referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class eksternNoekkel {
        
        private string fagsystemField;
        
        private string noekkelField;
        
        /// <remarks/>
        public string fagsystem {
            get {
                return this.fagsystemField;
            }
            set {
                this.fagsystemField = value;
            }
        }
        
        /// <remarks/>
        public string noekkel {
            get {
                return this.noekkelField;
            }
            set {
                this.noekkelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class journalpostNoekler : registreringNoekler {
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private string journalposttypeField;
        
        private string journalstatusField;
        
        private System.DateTime journaldatoField;
        
        private bool journaldatoFieldSpecified;
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime mottattDatoField;
        
        private bool mottattDatoFieldSpecified;
        
        private System.DateTime sendtDatoField;
        
        private bool sendtDatoFieldSpecified;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        private System.DateTime offentlighetsvurdertDatoField;
        
        private bool offentlighetsvurdertDatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
            }
        }
        
        /// <remarks/>
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool journaldatoSpecified {
            get {
                return this.journaldatoFieldSpecified;
            }
            set {
                this.journaldatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mottattDato {
            get {
                return this.mottattDatoField;
            }
            set {
                this.mottattDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mottattDatoSpecified {
            get {
                return this.mottattDatoFieldSpecified;
            }
            set {
                this.mottattDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sendtDato {
            get {
                return this.sendtDatoField;
            }
            set {
                this.sendtDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendtDatoSpecified {
            get {
                return this.sendtDatoFieldSpecified;
            }
            set {
                this.sendtDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime offentlighetsvurdertDato {
            get {
                return this.offentlighetsvurdertDatoField;
            }
            set {
                this.offentlighetsvurdertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offentlighetsvurdertDatoSpecified {
            get {
                return this.offentlighetsvurdertDatoFieldSpecified;
            }
            set {
                this.offentlighetsvurdertDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class partNoekler {
        
        private string partIDField;
        
        /// <remarks/>
        public string partID {
            get {
                return this.partIDField;
            }
            set {
                this.partIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saksmappeNoekler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class mappeNoekler {
        
        private systemID systemIDField;
        
        private string mappeIDField;
        
        private systemID referanseForeldermappeField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private partNoekler[] partField;
        
        private eksternNoekkel referanseEksternNoekkelField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        public systemID ReferanseForeldermappe {
            get {
                return this.referanseForeldermappeField;
            }
            set {
                this.referanseForeldermappeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public partNoekler[] part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        public eksternNoekkel referanseEksternNoekkel {
            get {
                return this.referanseEksternNoekkelField;
            }
            set {
                this.referanseEksternNoekkelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappeNoekler))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registreringNoekler))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/noekler/v1")]
    public partial class saksmappeNoekler : mappeNoekler {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private System.DateTime saksdatoField;
        
        private bool saksdatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime saksdato {
            get {
                return this.saksdatoField;
            }
            set {
                this.saksdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saksdatoSpecified {
            get {
                return this.saksdatoFieldSpecified;
            }
            set {
                this.saksdatoFieldSpecified = value;
            }
        }
    }
}
