//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace no.ks.fiks.io.arkiv.innsyn.sok.resultat.minimum {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1", IsNullable=false)]
    public partial class sokeresultatMinimum {
        
        private string systemField;
        
        private string meldingIdField;
        
        private string svarPaMeldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int takeField;
        
        private int skipField;
        
        private int countField;
        
        private resultatTypeMinimum resultattypeField;
        
        private resultatMinimum[] resultatListeField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public string svarPaMeldingId {
            get {
                return this.svarPaMeldingIdField;
            }
            set {
                this.svarPaMeldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int take {
            get {
                return this.takeField;
            }
            set {
                this.takeField = value;
            }
        }
        
        /// <remarks/>
        public int skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public resultatTypeMinimum resultattype {
            get {
                return this.resultattypeField;
            }
            set {
                this.resultattypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public resultatMinimum[] resultatListe {
            get {
                return this.resultatListeField;
            }
            set {
                this.resultatListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    public enum resultatTypeMinimum {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        saksmappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        journalpost,
        
        /// <remarks/>
        dokumentbeskrivelse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/sokeresultat/v1")]
    public partial class resultatMinimum {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse", typeof(dokumentbeskrivelseMinimum))]
        [System.Xml.Serialization.XmlElementAttribute("journalpost", typeof(journalpostMinimum))]
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappeMinimum))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registreringMinimum))]
        [System.Xml.Serialization.XmlElementAttribute("saksmappe", typeof(saksmappeMinimum))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class dokumentbeskrivelseMinimum {
        
        private systemID systemIDField;
        
        private string dokumenttypeField;
        
        private string dokumentstatusField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string[] forfatterField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string dokumentmediumField;
        
        private string oppbevaringsstedField;
        
        private string[] referanseArkivdelField;
        
        private string tilknyttetRegistreringSomField;
        
        private string dokumentnummerField;
        
        private System.DateTime tilknyttetDatoField;
        
        private string tilknyttetAvField;
        
        private slettingMinimum slettingField;
        
        private skjermingMinimum skjermingField;
        
        private graderingMinimum graderingField;
        
        private elektroniskSignaturMinimum elektroniskSignaturField;
        
        private dokumentobjektMinimum[] dokumentobjektField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string dokumenttype {
            get {
                return this.dokumenttypeField;
            }
            set {
                this.dokumenttypeField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentstatus {
            get {
                return this.dokumentstatusField;
            }
            set {
                this.dokumentstatusField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        public string oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public string tilknyttetRegistreringSom {
            get {
                return this.tilknyttetRegistreringSomField;
            }
            set {
                this.tilknyttetRegistreringSomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string dokumentnummer {
            get {
                return this.dokumentnummerField;
            }
            set {
                this.dokumentnummerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tilknyttetDato {
            get {
                return this.tilknyttetDatoField;
            }
            set {
                this.tilknyttetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string tilknyttetAv {
            get {
                return this.tilknyttetAvField;
            }
            set {
                this.tilknyttetAvField = value;
            }
        }
        
        /// <remarks/>
        public slettingMinimum sletting {
            get {
                return this.slettingField;
            }
            set {
                this.slettingField = value;
            }
        }
        
        /// <remarks/>
        public skjermingMinimum skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public graderingMinimum gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        public elektroniskSignaturMinimum elektroniskSignatur {
            get {
                return this.elektroniskSignaturField;
            }
            set {
                this.elektroniskSignaturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public dokumentobjektMinimum[] dokumentobjekt {
            get {
                return this.dokumentobjektField;
            }
            set {
                this.dokumentobjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2")]
    public partial class systemID {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class presedensMinimum {
        
        private System.DateTime presedensDatoField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string presedensHjemmelField;
        
        private string rettskildefaktorField;
        
        private System.DateTime presedensGodkjentDatoField;
        
        private bool presedensGodkjentDatoFieldSpecified;
        
        private string presedensGodkjentAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private string presedensStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime presedensDato {
            get {
                return this.presedensDatoField;
            }
            set {
                this.presedensDatoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string presedensHjemmel {
            get {
                return this.presedensHjemmelField;
            }
            set {
                this.presedensHjemmelField = value;
            }
        }
        
        /// <remarks/>
        public string rettskildefaktor {
            get {
                return this.rettskildefaktorField;
            }
            set {
                this.rettskildefaktorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime presedensGodkjentDato {
            get {
                return this.presedensGodkjentDatoField;
            }
            set {
                this.presedensGodkjentDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presedensGodkjentDatoSpecified {
            get {
                return this.presedensGodkjentDatoFieldSpecified;
            }
            set {
                this.presedensGodkjentDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string presedensGodkjentAv {
            get {
                return this.presedensGodkjentAvField;
            }
            set {
                this.presedensGodkjentAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        public string presedensStatus {
            get {
                return this.presedensStatusField;
            }
            set {
                this.presedensStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class avskrivningMinimum {
        
        private System.DateTime avskrivningsdatoField;
        
        private string avskrevetAvField;
        
        private string avskrivningsmaateField;
        
        private string referanseAvskrivesAvJournalpostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime avskrivningsdato {
            get {
                return this.avskrivningsdatoField;
            }
            set {
                this.avskrivningsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string avskrevetAv {
            get {
                return this.avskrevetAvField;
            }
            set {
                this.avskrevetAvField = value;
            }
        }
        
        /// <remarks/>
        public string avskrivningsmaate {
            get {
                return this.avskrivningsmaateField;
            }
            set {
                this.avskrivningsmaateField = value;
            }
        }
        
        /// <remarks/>
        public string referanseAvskrivesAvJournalpost {
            get {
                return this.referanseAvskrivesAvJournalpostField;
            }
            set {
                this.referanseAvskrivesAvJournalpostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class korrespondansepartMinimum {
        
        private string korrespondanseparttypeField;
        
        private string korrespondansepartNavnField;
        
        private string[] postadresseField;
        
        private string postnummerField;
        
        private string poststedField;
        
        private string landField;
        
        private string epostadresseField;
        
        private string[] telefonnummerField;
        
        private string kontaktpersonField;
        
        private string administrativEnhetField;
        
        private string saksbehandlerField;
        
        /// <remarks/>
        public string korrespondanseparttype {
            get {
                return this.korrespondanseparttypeField;
            }
            set {
                this.korrespondanseparttypeField = value;
            }
        }
        
        /// <remarks/>
        public string korrespondansepartNavn {
            get {
                return this.korrespondansepartNavnField;
            }
            set {
                this.korrespondansepartNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postadresse")]
        public string[] postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
            }
        }
        
        /// <remarks/>
        public string postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public string epostadresse {
            get {
                return this.epostadresseField;
            }
            set {
                this.epostadresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefonnummer")]
        public string[] telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        public string kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksbehandler {
            get {
                return this.saksbehandlerField;
            }
            set {
                this.saksbehandlerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class konverteringMinimum {
        
        private System.DateTime konvertertDatoField;
        
        private string konvertertAvField;
        
        private string konvertertFraFormatField;
        
        private string konvertertTilFormatField;
        
        private string konverteringsverktoeyField;
        
        private string konverteringskommentarField;
        
        /// <remarks/>
        public System.DateTime konvertertDato {
            get {
                return this.konvertertDatoField;
            }
            set {
                this.konvertertDatoField = value;
            }
        }
        
        /// <remarks/>
        public string konvertertAv {
            get {
                return this.konvertertAvField;
            }
            set {
                this.konvertertAvField = value;
            }
        }
        
        /// <remarks/>
        public string konvertertFraFormat {
            get {
                return this.konvertertFraFormatField;
            }
            set {
                this.konvertertFraFormatField = value;
            }
        }
        
        /// <remarks/>
        public string konvertertTilFormat {
            get {
                return this.konvertertTilFormatField;
            }
            set {
                this.konvertertTilFormatField = value;
            }
        }
        
        /// <remarks/>
        public string konverteringsverktoey {
            get {
                return this.konverteringsverktoeyField;
            }
            set {
                this.konverteringsverktoeyField = value;
            }
        }
        
        /// <remarks/>
        public string konverteringskommentar {
            get {
                return this.konverteringskommentarField;
            }
            set {
                this.konverteringskommentarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class dokumentobjektMinimum {
        
        private systemID systemIDField;
        
        private string versjonsnummerField;
        
        private string variantformatField;
        
        private string formatField;
        
        private string formatDetaljerField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string referanseDokumentfilField;
        
        private string sjekksumField;
        
        private string sjekksumAlgoritmeField;
        
        private string filstoerrelseField;
        
        private elektroniskSignaturMinimum elektroniskSignaturField;
        
        private konverteringMinimum[] konverteringField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string versjonsnummer {
            get {
                return this.versjonsnummerField;
            }
            set {
                this.versjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        public string variantformat {
            get {
                return this.variantformatField;
            }
            set {
                this.variantformatField = value;
            }
        }
        
        /// <remarks/>
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string formatDetaljer {
            get {
                return this.formatDetaljerField;
            }
            set {
                this.formatDetaljerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string referanseDokumentfil {
            get {
                return this.referanseDokumentfilField;
            }
            set {
                this.referanseDokumentfilField = value;
            }
        }
        
        /// <remarks/>
        public string sjekksum {
            get {
                return this.sjekksumField;
            }
            set {
                this.sjekksumField = value;
            }
        }
        
        /// <remarks/>
        public string sjekksumAlgoritme {
            get {
                return this.sjekksumAlgoritmeField;
            }
            set {
                this.sjekksumAlgoritmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string filstoerrelse {
            get {
                return this.filstoerrelseField;
            }
            set {
                this.filstoerrelseField = value;
            }
        }
        
        /// <remarks/>
        public elektroniskSignaturMinimum elektroniskSignatur {
            get {
                return this.elektroniskSignaturField;
            }
            set {
                this.elektroniskSignaturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("konvertering")]
        public konverteringMinimum[] konvertering {
            get {
                return this.konverteringField;
            }
            set {
                this.konverteringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class elektroniskSignaturMinimum {
        
        private string elektroniskSignaturSikkerhetsnivaaField;
        
        private string elektroniskSignaturVerifisertField;
        
        private System.DateTime verifisertDatoField;
        
        private string verifisertAvField;
        
        /// <remarks/>
        public string elektroniskSignaturSikkerhetsnivaa {
            get {
                return this.elektroniskSignaturSikkerhetsnivaaField;
            }
            set {
                this.elektroniskSignaturSikkerhetsnivaaField = value;
            }
        }
        
        /// <remarks/>
        public string elektroniskSignaturVerifisert {
            get {
                return this.elektroniskSignaturVerifisertField;
            }
            set {
                this.elektroniskSignaturVerifisertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime verifisertDato {
            get {
                return this.verifisertDatoField;
            }
            set {
                this.verifisertDatoField = value;
            }
        }
        
        /// <remarks/>
        public string verifisertAv {
            get {
                return this.verifisertAvField;
            }
            set {
                this.verifisertAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class slettingMinimum {
        
        private string slettingstypeField;
        
        private System.DateTime slettetDatoField;
        
        private string slettetAvField;
        
        /// <remarks/>
        public string slettingstype {
            get {
                return this.slettingstypeField;
            }
            set {
                this.slettingstypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime slettetDato {
            get {
                return this.slettetDatoField;
            }
            set {
                this.slettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string slettetAv {
            get {
                return this.slettetAvField;
            }
            set {
                this.slettetAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpostMinimum))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class registreringMinimum {
        
        private systemID systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private System.DateTime arkivertDatoField;
        
        private string arkivertAvField;
        
        private string[] referanseArkivdelField;
        
        private skjermingMinimum skjermingField;
        
        private graderingMinimum graderingField;
        
        private dokumentbeskrivelseMinimum[] dokumentbeskrivelseField;
        
        private string registreringsIDField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private string[] forfatterField;
        
        private string dokumentmediumField;
        
        private string[] oppbevaringsstedField;
        
        private korrespondansepartMinimum[] korrespondansepartField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arkivertDato {
            get {
                return this.arkivertDatoField;
            }
            set {
                this.arkivertDatoField = value;
            }
        }
        
        /// <remarks/>
        public string arkivertAv {
            get {
                return this.arkivertAvField;
            }
            set {
                this.arkivertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public skjermingMinimum skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public graderingMinimum gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public dokumentbeskrivelseMinimum[] dokumentbeskrivelse {
            get {
                return this.dokumentbeskrivelseField;
            }
            set {
                this.dokumentbeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string registreringsID {
            get {
                return this.registreringsIDField;
            }
            set {
                this.registreringsIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepart")]
        public korrespondansepartMinimum[] korrespondansepart {
            get {
                return this.korrespondansepartField;
            }
            set {
                this.korrespondansepartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class skjermingMinimum {
        
        private string tilgangsrestriksjonField;
        
        private string skjermingshjemmelField;
        
        private string[] skjermingMetadataField;
        
        private string skjermingDokumentField;
        
        private string skjermingsvarighetField;
        
        private System.DateTime skjermingOpphoererDatoField;
        
        private bool skjermingOpphoererDatoFieldSpecified;
        
        /// <remarks/>
        public string tilgangsrestriksjon {
            get {
                return this.tilgangsrestriksjonField;
            }
            set {
                this.tilgangsrestriksjonField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingshjemmel {
            get {
                return this.skjermingshjemmelField;
            }
            set {
                this.skjermingshjemmelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("skjermingMetadata")]
        public string[] skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingDokument {
            get {
                return this.skjermingDokumentField;
            }
            set {
                this.skjermingDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string skjermingsvarighet {
            get {
                return this.skjermingsvarighetField;
            }
            set {
                this.skjermingsvarighetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime skjermingOpphoererDato {
            get {
                return this.skjermingOpphoererDatoField;
            }
            set {
                this.skjermingOpphoererDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skjermingOpphoererDatoSpecified {
            get {
                return this.skjermingOpphoererDatoFieldSpecified;
            }
            set {
                this.skjermingOpphoererDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class graderingMinimum {
        
        private string gradField;
        
        private System.DateTime graderingsdatoField;
        
        private string gradertAvField;
        
        private System.DateTime nedgraderingsdatoField;
        
        private bool nedgraderingsdatoFieldSpecified;
        
        private string nedgradertAvField;
        
        /// <remarks/>
        public string grad {
            get {
                return this.gradField;
            }
            set {
                this.gradField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime graderingsdato {
            get {
                return this.graderingsdatoField;
            }
            set {
                this.graderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string gradertAv {
            get {
                return this.gradertAvField;
            }
            set {
                this.gradertAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime nedgraderingsdato {
            get {
                return this.nedgraderingsdatoField;
            }
            set {
                this.nedgraderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nedgraderingsdatoSpecified {
            get {
                return this.nedgraderingsdatoFieldSpecified;
            }
            set {
                this.nedgraderingsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string nedgradertAv {
            get {
                return this.nedgradertAvField;
            }
            set {
                this.nedgradertAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class journalpostMinimum : registreringMinimum {
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private string journalposttypeField;
        
        private string journalstatusField;
        
        private System.DateTime journaldatoField;
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime mottattDatoField;
        
        private bool mottattDatoFieldSpecified;
        
        private System.DateTime sendtDatoField;
        
        private bool sendtDatoFieldSpecified;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        private System.DateTime offentlighetsvurdertDatoField;
        
        private bool offentlighetsvurdertDatoFieldSpecified;
        
        private string antallVedleggField;
        
        private avskrivningMinimum[] avskrivningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public string journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
            }
        }
        
        /// <remarks/>
        public string journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mottattDato {
            get {
                return this.mottattDatoField;
            }
            set {
                this.mottattDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mottattDatoSpecified {
            get {
                return this.mottattDatoFieldSpecified;
            }
            set {
                this.mottattDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sendtDato {
            get {
                return this.sendtDatoField;
            }
            set {
                this.sendtDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendtDatoSpecified {
            get {
                return this.sendtDatoFieldSpecified;
            }
            set {
                this.sendtDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime offentlighetsvurdertDato {
            get {
                return this.offentlighetsvurdertDatoField;
            }
            set {
                this.offentlighetsvurdertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offentlighetsvurdertDatoSpecified {
            get {
                return this.offentlighetsvurdertDatoFieldSpecified;
            }
            set {
                this.offentlighetsvurdertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string antallVedlegg {
            get {
                return this.antallVedleggField;
            }
            set {
                this.antallVedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avskrivning")]
        public avskrivningMinimum[] avskrivning {
            get {
                return this.avskrivningField;
            }
            set {
                this.avskrivningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class kassasjonMinimum {
        
        private string kassasjonsvedtakField;
        
        private string kassasjonshjemmelField;
        
        private string bevaringstidField;
        
        private System.DateTime kassasjonsdatoField;
        
        /// <remarks/>
        public string kassasjonsvedtak {
            get {
                return this.kassasjonsvedtakField;
            }
            set {
                this.kassasjonsvedtakField = value;
            }
        }
        
        /// <remarks/>
        public string kassasjonshjemmel {
            get {
                return this.kassasjonshjemmelField;
            }
            set {
                this.kassasjonshjemmelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string bevaringstid {
            get {
                return this.bevaringstidField;
            }
            set {
                this.bevaringstidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime kassasjonsdato {
            get {
                return this.kassasjonsdatoField;
            }
            set {
                this.kassasjonsdatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saksmappeMinimum))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class mappeMinimum {
        
        private systemID systemIDField;
        
        private string mappeIDField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string dokumentmediumField;
        
        private string[] oppbevaringsstedField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private string avsluttetAvField;
        
        private string[] referanseArkivdelField;
        
        private kassasjonMinimum kassasjonField;
        
        private skjermingMinimum skjermingField;
        
        private graderingMinimum graderingField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public systemID systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public kassasjonMinimum kassasjon {
            get {
                return this.kassasjonField;
            }
            set {
                this.kassasjonField = value;
            }
        }
        
        /// <remarks/>
        public skjermingMinimum skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public graderingMinimum gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappeMinimum))]
        [System.Xml.Serialization.XmlElementAttribute("registrering", typeof(registreringMinimum))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ks.no/standarder/fiks/arkiv/arkivstruktur/minimum/v1")]
    public partial class saksmappeMinimum : mappeMinimum {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private System.DateTime saksdatoField;
        
        private string administrativEnhetField;
        
        private string saksansvarligField;
        
        private string journalenhetField;
        
        private string saksstatusField;
        
        private System.DateTime utlaantDatoField;
        
        private bool utlaantDatoFieldSpecified;
        
        private string utlaantTilField;
        
        private string[] referanseSekundaerKlassifikasjonField;
        
        private presedensMinimum[] presedensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime saksdato {
            get {
                return this.saksdatoField;
            }
            set {
                this.saksdatoField = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksansvarlig {
            get {
                return this.saksansvarligField;
            }
            set {
                this.saksansvarligField = value;
            }
        }
        
        /// <remarks/>
        public string journalenhet {
            get {
                return this.journalenhetField;
            }
            set {
                this.journalenhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksstatus {
            get {
                return this.saksstatusField;
            }
            set {
                this.saksstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime utlaantDato {
            get {
                return this.utlaantDatoField;
            }
            set {
                this.utlaantDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utlaantDatoSpecified {
            get {
                return this.utlaantDatoFieldSpecified;
            }
            set {
                this.utlaantDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string utlaantTil {
            get {
                return this.utlaantTilField;
            }
            set {
                this.utlaantTilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseSekundaerKlassifikasjon")]
        public string[] referanseSekundaerKlassifikasjon {
            get {
                return this.referanseSekundaerKlassifikasjonField;
            }
            set {
                this.referanseSekundaerKlassifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public presedensMinimum[] presedens {
            get {
                return this.presedensField;
            }
            set {
                this.presedensField = value;
            }
        }
    }
}
